## \hfil ACKNOWLEDMENTS\hfil

We are grateful to various museums and their staff for providing access to the collections and materials used in this study, including the University of Kansas Natural History Museum, the Kansas State Historical Society, the University of Colorado, the Nebraska State Museum, the University of Texas, and the University of Wyoming. MEH is thankful for financial support from the University of Iowa, the Arizona State Museum Thompson Fund (U of Arizona), the Emily W. Haury Education Fund for Archaeology (U of Arizona), and the George C. Frison Institute Paleoindian Grant (U Wyoming) that facilitated museum visits. MEH thanks Kevin Flaherty for his help in the early stages of data collection and the statistical advice provided by Rhonda R. DeCook, Feiran Jiao, and Barbara Monaco. EOC is grateful to Sarah N. Coon for help with manuscript editing. Partial funding for this project was provided by Purdue University College of Liberal Arts’ Exploratory Research in the Social Sciences award and the Margo Katherine Wilke research internship fund.
