## \hfil CONCLUSION\hfil

Popular accounts of indigenous life in the North American Great Plains portray a way of life and diet that was highly contingent on the vast herds of bison that roamed the region. Although romantic to some, this depiction is simplistic and does not acknowledge the multidimensional character of the Plains’ indigenous people. Our study examined evidence representing over 13,000 years of this region’s cultural history, finding that people exhibited remarkable variation in behaviors and dietary strategies. We conclude that even though the Plains people maintained a way of life associated with bison over time, bison was not the dominant species in their diet. Instead, people responded to marked climatic and habitat variability across space and time by adjusting their hunting strategies accordingly.  

To conduct this study, we developed a useful framework for understanding dietary strategies. We conceptualized a diversification and specialization “space” using indices of richness and evenness in order to characterize the hunting strategies of indigenous people on the Great Plains great plains were located,and to quantify changes over time. We have identified four discrete locations in the diversity space – diversification, hyper-diversification, specialization, and hyper-specialization – but do so out of pure convenience. In fact, these locations are not discrete, but comprise a continuous space that, in its current form, is relative to the assemblages in this sample. Nonetheless, we believe that this framework can be useful for comparing and measuring changes in the foraging strategies of small-scale societies over time.

The evolution of hunting strategies and dietary variation that we observed on the Great Plains zooarchaeological record does not support a model of progressive resource intensification from hunting and gathering to farming. Rather, the data support a model of constant diversification of continuous hunting strategies from, starting with the Paleoindian through the Late Prehistoric periods. In this model, hunters on the Plains (and elsewhere) maintained a consistently high diversity of behavioral strategies. This highly flexible and diversified portfolio of dietary strategies enabled the people of the Great Plains to adapt their approaches to procuring food across different habitats and time periods.
