## \hfil INTRODUCTION\hfil


Studies of dietary diversity are prominent in the zooarchaeological literature and have been pivotal to understanding prehistoric economies. Investigations of diachronic changes in economic strategies have focused on a broad selection of topics, including human–environment interactions, ecological adaptations, the origins of farming, human-caused extinctions and animal translocation, and the development of social complexity [e.g., @boivin_ecological_2016; @broughton_resource_1999; @broughton_prey_2002; @deangelis_evaluation_2018; @munro_emergence_2018; @nagaoka_effects_2002; @stiner_tortoise_2000; @weitzel_declining_2019]. Such studies often attempt to understand the factors contributing to changes in dietary diversity, focusing on the idea of resource intensification, or Boserup’s Theory, which is commonly defined as the ability of human populations to obtain more food in a given unit of time, labor, or space [@binford_constructing_2001: 357; @boserup_conditions_1965; @broughton_late_1994].

Boserup posited that when humans intensify food production, they incur a decline in productive efficiency, as increasing the food yield involves a disproportionate increase in costs relative to gains. Anthropologists have vigorously debated Boserup's Theory and the definition of intensification [@betts_quantifying_2004; @earle_model_1980; @matson_intensification_1983; @morrison_intensification_1994]. Some have argued that intensification can occur even without a decline in efficiency [e.g., @brookfield_intensification_1972; @leach_intensification_1999; @morgan_is_2015; @morrison_intensification_1994]. Others have focused on understanding what they call the “component strategies” of resource intensification, or what we term the “mechanisms” of intensification: specialization, diversification, and investment [@betts_quantifying_2004; @morrison_intensification_1994]. In zooarchaeology, specialization refers to economic strategies through which hunters focus on procuring a narrow range of species, typically with an associated decline in the procurement of other species; [@lyman_seal_1989, @lyman_subsistence_1991]. Diversification, meanwhile, is a strategy through which hunters rely on a broader range of food species or change the organization of the types of species procured.

Archaeologists have observed material culture representing both diversified and specialized economies across the North American Great Plains and its adjacent regions. Economic systems in this region have a record of at least 13,000 years of variation, likely due, at least partially, to diachronic [temporal] and synchronic [regional] variability in environmental conditions, and human and prey population pressures. Despite this variation, an apparent big-game hunting specialization seems to have persisted in this region alongside more diversified strategies, including a broad spectrum of small-to-medium-sized prey [@kelly_coming_1988]. This hunting-focused specialization lasted much longer than it did in many other regions of North America, where domesticates were adopted earlier [@fagan_ancient_2018; @neusius_seeking_2013]. Early Great Plains archaeologists have proposed a simplified progression of subsistence intensification through time. This starts with specialized big-game hunters in the Paleoindian period [13,500–9,000 BP] to the Late Prehistoric period [1000–300 BP], which was then characterized by a diversified economy that included gathered, hunted, and domesticated resources [e.g., @lehmer_introduction_1971: 30-33; @liberty_anthropology_1980: 37-41; @wedel_cultural_1940; @wedel_aspects_1953: 509].

Although recent research has presented much more nuanced inferences regarding the subsistence economies of peoples on the Great Plains, the apparent trend toward resource intensification has remained a clear pattern. For example, researchers have begun to question the traditional view of Paleoindians as big prey hunting specialists [@blackmar_paleoarchaic_2006; @deangelis_evaluation_2018; @hill_causes_2007a, @hill_variation_2008; @kornfeld_bonebeds_2008; @kornfeld_nelson_2007]. Studies of later periods on the Plains have acknowledged a broader range of regional variability in subsistence practices, including an increasing diversity of hunted and gathered foods. Researchers have also documented the appearance and intensification of domesticated resources during the Woodland and Late Prehistoric periods [e.g., @adair_patterns_2011; @bozell_native_2011]. Investigating the economic variability observed across this vast region has great potential to shed light on the broad range of behaviors and technologies driving the intensification mechanisms used by human populations to produce food. 

Consequently, this study investigates the broad patterns of change in the economic strategies used by Great Plains indigenous communities in order to evaluate the hypothesis that prehistoric small-scale societies of the Great Plains increasingly and unidirectionally intensified their resource base over time. We examine the hunting and gathering economies of the Paleoindian period through to the farming societies of the Late Prehistoric period to compare how populations approached the intensification of a nearly identical suite of faunal resources. We focus on the long-term use of intensification mechanisms within major habitat settings of the Great Plains and the Rocky Mountains, including alluvial valleys, foothills and mountains, and plains and rolling hills [@hill_variation_2008; @knell_linking_2012].

To evaluate this hypothesis and track subsistence shifts through time, we use faunal evidence of more than 200 zooarchaeological assemblages from across the North American Great Plains and adjacent regions, dating from the last 13,500 years. We assess the variability of dietary diversity via species richness and evenness, including the relative ratios of different sized prey, across the geographical extent of the Great Plains through time. In doing so, this study yields a better understanding of the long-term trends in the intensification of the human use of animals in this region. 

Before describing the methods and results of this study, we provide a summary of prior zooarchaeological approaches to the study of animal resource intensification. In part, we discuss how our preceding work on Paleoindian subsistence has laid the foundation for a comparative study of later periods. The large temporal scale of our study provides a more comprehensive understanding of the economic strategies of Great Plains prehistoric foragers and farmers within the changing paleoenvironmental conditions in which these groups lived.