## \hfil ZOOARCHAEOLOGICAL APPROACHES TO INTENSIFICATION\hfil

@boserup_conditions_1965 coined the term resource intensification in response to contemporary economists’ application of the Malthusian paradigm [@malthus_essay_1798] for understanding the population dynamics of small-scale farming societies. Boserup argued that, from a Malthusian perspective, small-scale farmers had little control over their population growth, which was instead controlled by the food supply available to these "primitive" farmers. In effect, the Malthusians viewed historical changes in human population sizes as the product of technological developments that generated increases in food productivity. For Boserup, however, the notion of food production as the ultimate limiting factor of population growth did not capture the reality of ancient and contemporary small-scale populations. Instead, this idea likely reflected contemporaneous Western European agricultural practices, which were characterized by extensive expansion to create new cultivation fields. By contrast, Boserup argued that human population growth was the driving force for increasing food productivity via intensive rather than extensive food production. 

Over the past 50 years, archaeologists have elaborated many definitions of resource intensification, often depending on the focus of the research, i.e., whether it is on agricultural or hunter-gatherer societies [@moss_understanding_2012; @thurston_seeking_2007]. Zooarchaeologists have argued that the increase in foraging productivity via intensification arises through the mechanisms of specialization, diversification, and investment [@butler_resource_2004; @moss_understanding_2012]. Diversification and specialization subsistence strategies are complex. Although one could assume that for past societies these strategies would be mutually exclusive, [@betts_quantifying_2004: 359] argue that this is an incorrect assumption. In fact, when considered over a long period of time, specialization and diversification may emerge as complementary strategies. Investment in new technologies or behaviors is often directly tied to strategies of specialization and diversification [ 1980; 2001 :189]. Yet, as @earle_model_1980 notes, increased investments and specialization may contribute to resource intensification only up to a point; only diversification will allow for further intensification. Below, we use these mechanisms to structure a summary of how recent zooarchaeologists have identified and used the concept of faunal resource intensification [@betts_quantifying_2004; @morrison_intensification_1994].

Especially in non-agricultural societies, archaeologists have often viewed specialization as a path to increased efficiency. In their discussion of the adaptations of the peopling of the Americas, @kelly_coming_1988 hypothesized that a high-technology, highly specialized big-prey hunting strategy might have enabled early foragers to move through the new landscape, regardless of the environmental setting or seasonality. Recent research has inferred that early hunters in North America were indeed big-game hunting specialists [e.g., @surovell_how_2008, @surovell_human_2009]; however, the hunting specialization hypothesis might be too simplistic to capture the variability of these foragers’ hunting behaviors [e.g.,  @cannon_explaining_2008; @deangelis_evaluation_2018; @haynes_clovis-era_2014; @hill_causes_2007a, @hill_variation_2008]. In addition, in studies of Paleoindian foraging and prey use in the Great Plains and Rocky Mountains Hill [@hill_causes_2007a, @hill_moveable_2007b, @hill_variation_2008; @hill_cody_2013; @knell_linking_2012] and @otarola-castillo_spatio-temporal_2016 have found statistically meaningful differences in prey use across habitats, potentially by the same hunting groups. For example, in the High Plains grasslands, there was low temporal and spatial predictability of important game and other biotic and non-biotic resources. This habitat likely provided a selective advantage for Paleoindian hunters to approach prey choice with a more specialist stance. At the same time, the same hunter may have found it better to practice a more generalist diet in an alluvial valley habitat, where resources were more predictable. These findings highlight the flexibility with which these early foraging groups behaved. 

Researchers studying North America during later periods have also observed specialization among hunter-gatherers. In the Northern Plains, for example, researchers have proposed that Middle Holocene [~8500–5500 years ago] foragers were specialized bison hunters, perhaps in response to the paucity of alternative plant or animal resources in the region [@forbis_one_1982; @frison_northwestern_1998a; @robertson_reassessing_2011]. Research from the Pacific Northwest has suggested a causal link between the economic surplus arising from fishing specialization and the region’s increasing social complexity over the last 3500 years [e.g., @butler_resource_2004; @coupland_you_2010; @fladmark_paleoecological_1975; @matson_prehistory_1995; @moss_understanding_2012].

Studies on the origins of herding and farming have frequently used Boserup’s Theory to explain that domestication was rooted in a decline in foraging efficiency [@weitzel_declining_2019]. However, there has been disagreement about whether declines in foraging efficiencies were due to population increases [i.e., demographic packing; @broughton_late_1994; @munro_small_2004; @munro_emergence_2018; @stiner_tortoise_2000; @stiner_paleolithic_1999] or environmental change [@gremillion_human_2009]. Most researchers who have examined the rise of farming in connection with foraging declines have inferred that the mechanism of resource intensification was diversification [@munro_epipaleolithic_2009; @zeder_broad_2012] as members of hunting and gathering economies adopted new strategies or technologies to exploit previously unrealized parts of their dietary niche. However, in this case, the increased cost of the behavioral or technological investment would have decreased the overall dietary efficiency [e.g., @bettinger_simple_2006; @munro_epipaleolithic_2009; @ugan_when_2003].

@flannery_archaeological_1968 famously coined the term Broad Spectrum Revolution [BSR] to describe the dietary diversification strategy adopted by foraging societies, which led to the emergence of Neolithic farmer societies as part of a long-term trend of resource intensification caused by increasing population pressures [see review in @zeder_broad_2012]. To investigate the hypotheses of the BSR, researchers have increasingly employed Optimal Foraging Theory [OFT] as a quantitative hypothesis testing framework [@broughton_evolutionary_2010; @byers_holocene_2004; @gremillion_seed_2004; @gremillion_particularism_2014; @winterhalder_optimal_1986] however, see a critique of OFT for studying the origins of domestication in [@smith_consumers_1996, @smith_comparison_2015; @zeder_broad_2012, @zeder_core_2015, @zeder_domestication_2016]. Classic OFT heuristics like the diet breadth model [DBM], also known as the prey model or prey choice model, predict when and how foragers will diversify their diet base. These models assume that foragers rank all prey according to their rate of energy acquisition over the time spent foraging [E/T] and that they tend to maximize this ratio. The DBM suggests that when high-ranked prey become scarcer, foragers should diversify their diet by including low E/T ranked prey.

In this context, OFT and the DBM have been successful at generating testable hypotheses regarding foraging and farming populations [@bettinger_marginal_2016; @bird_behavioral_2006]. However, Stiner and colleagues [@stiner_thirty_2001; @stiner_approaches_2002; @stiner_tortoise_2000; @stiner_paleolithic_1999; @zeder_broad_2012] have challenged Flannery’s original conceptualization of the BSR in the Mediterranean Basin based on their application of foraging theory. Rather than following traditional Linnaean taxonomic categories, Stiner and colleagues used alternative classifications as the basis for measuring the change in dietary diversity. They argued that there were clear archaeological signals for the BSR when focusing on the practical differences between prey, for example, the prey handling costs [e.g., pursuit, capture, and processing] associated with pursuing small vs. large prey. Results of Stiner and colleagues’ work showed that Mediterranean societies during the Late Pleistocene shifted away from slow-moving prey, such as tortoises and shellfish, and increasingly began including fast-moving prey, such as birds, hares, and rabbits, in their diet. The researchers attributed these changes in prey use to demographically driven resource pressures. 

In North America, there have been numerous applications of OFT principles in order to understand the subsistence strategies of hunter-gatherer and farming populations [@bettinger_marginal_2016; @bird_behavioral_2006]. For example, @barlow_predicting_2002 argued that increases in maize agriculture in the Great Basin were likely due to long-term decreases in wild prey and plant resources. @broughton_widening_1997 @broughton_resource_1999 showed that occupants of the Emeryville Shell mound in San Francisco Bay broadened their diet breadth by including low-ranked prey such as marine mammals, mollusks, small fish, and acorns. Broughton proposed that this type of resource intensification was a response to declines in high-ranked prey such as elk, deer, and large fish. Likewise, the McElmo Dome area of Mesa Verde, in southwestern Colorado, provides an example of macro-nutrient intensification. In this study, @ellyson_animal_2019 used predictions from OFT to contextualize their analysis of faunal remains left by farmer-gatherer-hunters who occupied the area during AD 900–1280. The subsistence system at Mesa Verde depended on both hunting and husbandry practices. However, when the availability of hunted prey declined, the people at Mesa Verde intensified turkey husbandry practices, likely in order to maintain appropriate levels of protein intake. In the Eastern United States, @weitzel_declining_2019 demonstrated that the overall foraging efficiency of hunted prey gradually declined in the middle Tennessee River; occupants responded by gradually intensifying their resources through dietary diversification. Finally, in the Mimbres Valley of New Mexico, @cannon_large_2001 investigated whether people there adopted farming as a form of resource intensification. As in Flannery’s BSR, dietary diversification might have played a precursory role in plant domestication in North America. Cannon documented that prey resource depression took place in the period immediately before the appearance of domestication in the region. Based on these results, Cannon argued that cultivation was indeed a form of resource intensification. 

Recent studies have shown that, even in situations with long-term intensification trends, such tendencies may not be unidirectional or uniform across habitats. @weitzel_declining_2019, for example, pointed out that, although foraging efficiency progressively declined in wetland patches, the same did not occur in terrestrial patches, where there was a general increase in foraging efficiency before initial domestication. Similarly, in a large faunal analysis from the Late Archaic through the Hohokam post-Classic period of the Sonoran desert, Dean and colleagues identified a pattern of intensification via diversification of hunting strategies, which seems to have taken place in the time leading up to the adoption of farming [@beaver_using_2019; @dean_hunting_2007, @dean_fauna_2017]. However, for the Hohokam groups in this study, the adoption of agriculture created constraints on hunting intensification through gendered labor demands associated with canal irrigation and associated anthropogenic modifications to the landscape. 

Investment is the last aspect of intensification. Humans and other animals differ in the degree to which they rely on technology to interact with their environment. Humans use a wide array of tools and features as part of their subsistence technology [@oswalt_anthropological_1976]. Hunters use weapons, tools, and structures to help them trap and kill their prey, process their carcasses, store animal products, cook or transform animal products into food and other useful products [e.g., clothes, shelter], and increase resource production when under population pressure [@flannery_cultural_1972: 417]. As discussed above, there is an assumption that better technology increases the number of resources acquired. However, that technology comes with a cost of time [labor] to acquire the raw material, produce the technology, and maintain or repair that technology [e.g., @bleed_optimal_1986; @bright_effect_2002; @kuhn_formal_1994; @metcalfe_model_1992]. As @ugan_when_2003 note, the costs of technology are just as substantial as the benefits derived from its use. We keep in mind two factors when comparing the time cost of technology. The first is the actual time invested in the creation and use of technology. The second is the time that hunters would otherwise spend foraging if the technology were not involved. As with all technology, its use is not always functional for maximizing returns. Decoration, construction, and use of technology also have symbolic or social values that are not viewed the same as caloric returns. 

Since Flannery formulated and popularized the idea of the BSR as a type of resource intensification, researchers have focused on discovering other formal intensification mechanisms that have driven many large-scale human economic transitions, often using zooarchaeological data. This study documents the intensification mechanisms employed over time on the Great Plains. In the following section, we provide a brief background on the cultural history and environmental constraints of this region. 
